### ISSUE TITLE
Where are the privacy and security settings on Mypal 74.1.0?

### ISSUE THREAD

**Issue by Sen-nin** [Feodor2/Mypal68#617]
Where are the privacy and security settings on Mypal 74.1.0? For example, where do we set up cookie preferences?

**Comment by Feodor2** [comment]
Fixed you take updated version

**Comment by Sen-nin** [comment]
I got it. I reported elsewhere already, but you cannot log in to Twitter on this version in case you missed my report.
